const std = @import("std");
const types = @import("types");
const depth = @import("depth");

// Re-export Image from types for backwards compatibility
pub const Image = types.Image;

// C API bindings, generated by translate-c in build.zig
const c = @import("c");

/// Error types for camera operations
pub const CameraError = error{
    InitFailed,
    NoDevice,
    PermissionDenied,
    SessionError,
    CaptureFailed,
    NotOpen,
    AlreadyOpen,
    Unknown,
};

/// Camera handle for capturing images
pub const Camera = struct {
    handle: c.CameraHandle,

    /// Create a new camera instance
    pub fn init() !Camera {
        const handle = c.camera_create();
        if (handle == null) {
            return CameraError.InitFailed;
        }
        return Camera{ .handle = handle };
    }

    /// Destroy the camera and free resources
    pub fn deinit(self: *Camera) void {
        c.camera_destroy(self.handle);
        self.handle = null;
    }

    /// Open the camera and start the capture session
    pub fn open(self: *Camera) !void {
        const result = c.camera_open(self.handle);
        try cameraErrorFromC(result);
    }

    /// Close the camera and stop the capture session
    pub fn close(self: *Camera) void {
        c.camera_close(self.handle);
    }

    /// Capture a single frame from the camera
    /// The returned image is valid until the next capture or close
    pub fn captureFrame(self: *Camera) !Image {
        var c_image: c.CameraImage = undefined;
        const result = c.camera_capture_frame(self.handle, &c_image);
        try cameraErrorFromC(result);

        const chroma: ?types.Chroma = if (c_image.chroma_data != null and c_image.chroma_height > 0)
            .{
                .data = c_image.chroma_data[0..(c_image.chroma_bytes_per_row * c_image.chroma_height)],
                .width = c_image.chroma_width,
                .height = c_image.chroma_height,
                .bytes_per_row = c_image.chroma_bytes_per_row,
            }
        else
            null;

        const mask: ?types.Mask = if (c_image.mask_data != null and c_image.mask_height > 0)
            .{
                .data = c_image.mask_data[0..(c_image.mask_bytes_per_row * c_image.mask_height)],
                .width = c_image.mask_width,
                .height = c_image.mask_height,
                .bytes_per_row = c_image.mask_bytes_per_row,
            }
        else
            null;

        return Image{
            .data = c_image.data[0..(c_image.bytes_per_row * c_image.height)],
            .width = c_image.width,
            .height = c_image.height,
            .bytes_per_row = c_image.bytes_per_row,
            .chroma = chroma,
            .mask = mask,
        };
    }

    /// Attach a depth model (or none); frames then carry a nearness mask.
    /// The model must outlive the camera's use of it.
    pub fn setDepthModel(self: *Camera, model: ?*depth.Model) void {
        c.camera_set_depth_model(self.handle, if (model) |m| m.handle else null);
    }

    /// Check if the camera is currently open
    pub fn isOpen(self: *Camera) bool {
        return c.camera_is_open(self.handle);
    }
};

/// Convert C error code to Zig error
fn cameraErrorFromC(code: c.CameraError) !void {
    switch (code) {
        c.CAMERA_OK => return,
        c.CAMERA_ERROR_INIT => return CameraError.InitFailed,
        c.CAMERA_ERROR_NO_DEVICE => return CameraError.NoDevice,
        c.CAMERA_ERROR_PERMISSION => return CameraError.PermissionDenied,
        c.CAMERA_ERROR_SESSION => return CameraError.SessionError,
        c.CAMERA_ERROR_CAPTURE => return CameraError.CaptureFailed,
        c.CAMERA_ERROR_NOT_OPEN => return CameraError.NotOpen,
        c.CAMERA_ERROR_ALREADY_OPEN => return CameraError.AlreadyOpen,
        else => return CameraError.Unknown,
    }
}

test "camera creation" {
    var camera = try Camera.init();
    defer camera.deinit();
    try std.testing.expect(camera.handle != null);
}

test "camera initial state" {
    var camera = try Camera.init();
    defer camera.deinit();
    try std.testing.expect(!camera.isOpen());
}

test "camera capture without open fails" {
    var camera = try Camera.init();
    defer camera.deinit();

    const result = camera.captureFrame();
    try std.testing.expectError(CameraError.NotOpen, result);
}

test "Image.getPixel" {
    const test_data = [_]u8{
        10, 20,  30,  40,
        50, 60,  70,  80,
        90, 100, 110, 120,
    };

    const image = Image{
        .data = &test_data,
        .width = 4,
        .height = 3,
        .bytes_per_row = 4,
    };

    // Test corner pixels
    try std.testing.expectEqual(@as(u8, 10), image.getPixel(0, 0));
    try std.testing.expectEqual(@as(u8, 40), image.getPixel(3, 0));
    try std.testing.expectEqual(@as(u8, 90), image.getPixel(0, 2));
    try std.testing.expectEqual(@as(u8, 120), image.getPixel(3, 2));

    // Test middle pixel
    try std.testing.expectEqual(@as(u8, 60), image.getPixel(1, 1));
}
