//! Monocular depth: a CoreML model turns a frame into a nearness map, and
//! this module knows where that model lives (an explicit path, or the cache
//! it is downloaded into on first use).
const std = @import("std");
const types = @import("types");
const Io = std.Io;

// CoreML/Vision bindings, generated by translate-c in build.zig
const c = @import("c");

pub const Error = error{
    LoadFailed,
    CompileFailed,
    InferenceFailed,
    UnsupportedModel,
};

/// A loaded depth model
pub const Model = struct {
    handle: c.DepthModelHandle,

    /// Load a model. `model_path` is an .mlpackage or a compiled .mlmodelc; a
    /// package is compiled once into `compiled_path`.
    pub fn init(model_path: [:0]const u8, compiled_path: [:0]const u8) Error!Model {
        var handle: c.DepthModelHandle = null;
        try check(c.depth_model_create(model_path.ptr, compiled_path.ptr, &handle));
        return .{ .handle = handle };
    }

    pub fn deinit(self: *Model) void {
        c.depth_model_destroy(self.handle);
        self.handle = null;
    }

    /// Nearness map (0 far .. 255 near) for an interleaved RGB image.
    /// Valid until the next estimate or deinit.
    pub fn estimateRgb(self: *Model, rgb: []const u8, width: u32, height: u32, bytes_per_row: u32) Error!types.Mask {
        var map: c.DepthMap = undefined;
        try check(c.depth_model_estimate_rgb(self.handle, rgb.ptr, width, height, bytes_per_row, &map));
        return .{
            .data = map.data[0 .. map.bytes_per_row * map.height],
            .width = map.width,
            .height = map.height,
            .bytes_per_row = map.bytes_per_row,
        };
    }
};

fn check(code: c.DepthError) Error!void {
    switch (code) {
        c.DEPTH_OK => return,
        c.DEPTH_ERROR_LOAD => return Error.LoadFailed,
        c.DEPTH_ERROR_COMPILE => return Error.CompileFailed,
        c.DEPTH_ERROR_INFERENCE => return Error.InferenceFailed,
        else => return Error.UnsupportedModel,
    }
}

// =============================================================================
// Locating the model
// =============================================================================

/// Apple's CoreML conversion of Depth Anything V2 (small, float16)
pub const default_model_name = "DepthAnythingV2SmallF16";
pub const download_base = "https://huggingface.co/apple/coreml-depth-anything-v2-small/resolve/main/" ++ default_model_name ++ ".mlpackage/";
pub const package_files = [_][]const u8{
    "Manifest.json",
    "Data/com.apple.CoreML/model.mlmodel",
    "Data/com.apple.CoreML/weights/weight.bin",
};
pub const download_size_mb = 48;

pub const cache_subdir = ".cache/dith";

pub const Paths = struct {
    /// The model to load (.mlpackage or .mlmodelc)
    model: [:0]u8,
    /// Where the compiled model lives (created on first load if needed)
    compiled: [:0]u8,

    pub fn deinit(self: Paths, gpa: std.mem.Allocator) void {
        gpa.free(self.model);
        gpa.free(self.compiled);
    }
};

pub const ResolveError = error{
    NoHomeDirectory,
    DownloadFailed,
    OutOfMemory,
};

/// Decide where the model is. An explicit path is used as-is (a package is
/// compiled into the cache). Otherwise the default model is downloaded into
/// `<home>/.cache/dith` when it is not there yet. Progress goes to `notice`.
pub fn resolvePaths(
    gpa: std.mem.Allocator,
    io: Io,
    home: ?[]const u8,
    explicit: ?[]const u8,
    notice: *Io.Writer,
) ResolveError!Paths {
    const home_dir = home orelse return ResolveError.NoHomeDirectory;
    const cache_dir = try std.fmt.allocPrint(gpa, "{s}/{s}", .{ home_dir, cache_subdir });
    defer gpa.free(cache_dir);

    if (explicit) |path| return explicitPaths(gpa, cache_dir, path);

    const model = try std.fmt.allocPrintSentinel(gpa, "{s}/{s}.mlpackage", .{ cache_dir, default_model_name }, 0);
    errdefer gpa.free(model);
    const compiled = try std.fmt.allocPrintSentinel(gpa, "{s}/{s}.mlmodelc", .{ cache_dir, default_model_name }, 0);
    errdefer gpa.free(compiled);

    try ensureDownloaded(gpa, io, model, notice);
    return .{ .model = model, .compiled = compiled };
}

/// Paths for a user-supplied model: compiled models load in place, packages
/// compile into the cache under their own name
pub fn explicitPaths(gpa: std.mem.Allocator, cache_dir: []const u8, path: []const u8) ResolveError!Paths {
    const model = try gpa.dupeZ(u8, path);
    errdefer gpa.free(model);
    if (std.mem.endsWith(u8, path, ".mlmodelc")) {
        const compiled = try gpa.dupeZ(u8, path);
        return .{ .model = model, .compiled = compiled };
    }
    const stem = std.fs.path.stem(std.fs.path.basename(path));
    const compiled = try std.fmt.allocPrintSentinel(gpa, "{s}/{s}.mlmodelc", .{ cache_dir, stem }, 0);
    return .{ .model = model, .compiled = compiled };
}

fn fileIsPresent(io: Io, path: []const u8) bool {
    const stat = Io.Dir.cwd().statFile(io, path, .{}) catch return false;
    return stat.size > 0;
}

fn ensureDownloaded(gpa: std.mem.Allocator, io: Io, package_dir: []const u8, notice: *Io.Writer) ResolveError!void {
    var missing = false;
    for (package_files) |name| {
        const path = try std.fmt.allocPrint(gpa, "{s}/{s}", .{ package_dir, name });
        defer gpa.free(path);
        if (!fileIsPresent(io, path)) missing = true;
    }
    if (!missing) return;

    notice.print("Downloading the depth model ({d} MB, one time) to {s}\n", .{ download_size_mb, package_dir }) catch {};
    notice.flush() catch {};

    var client: std.http.Client = .{ .allocator = gpa, .io = io };
    defer client.deinit();

    for (package_files) |name| {
        const path = try std.fmt.allocPrint(gpa, "{s}/{s}", .{ package_dir, name });
        defer gpa.free(path);
        if (fileIsPresent(io, path)) continue;

        const url = try std.fmt.allocPrint(gpa, "{s}{s}", .{ download_base, name });
        defer gpa.free(url);
        const partial = try std.fmt.allocPrint(gpa, "{s}.part", .{path});
        defer gpa.free(partial);

        notice.print("  {s}\n", .{name}) catch {};
        notice.flush() catch {};

        download(gpa, io, &client, url, path, partial) catch return ResolveError.DownloadFailed;
    }
}

fn download(gpa: std.mem.Allocator, io: Io, client: *std.http.Client, url: []const u8, path: []const u8, partial: []const u8) !void {
    const cwd = Io.Dir.cwd();
    try cwd.createDirPath(io, std.fs.path.dirname(path) orelse ".");

    // Write to a side file so an interrupted download never looks complete
    const file = try cwd.createFile(io, partial, .{});
    var closed = false;
    defer if (!closed) file.close(io);

    var write_buffer: [64 * 1024]u8 = undefined;
    var file_writer = file.writerStreaming(io, &write_buffer);
    var redirect_buffer: [4096]u8 = undefined;
    const result = try client.fetch(.{
        .location = .{ .url = url },
        .response_writer = &file_writer.interface,
        .redirect_buffer = &redirect_buffer,
        .redirect_behavior = @enumFromInt(8),
    });
    try file_writer.interface.flush();
    file.close(io);
    closed = true;
    _ = gpa;

    if (result.status != .ok) return error.DownloadFailed;
    try Io.Dir.rename(cwd, partial, cwd, path, io);
}

// =============================================================================
// Tests
// =============================================================================

test "explicitPaths compiles packages into the cache and loads compiled models in place" {
    const gpa = std.testing.allocator;

    const package = try explicitPaths(gpa, "/home/x/.cache/dith", "/models/MyDepth.mlpackage");
    defer package.deinit(gpa);
    try std.testing.expectEqualStrings("/models/MyDepth.mlpackage", package.model);
    try std.testing.expectEqualStrings("/home/x/.cache/dith/MyDepth.mlmodelc", package.compiled);

    const compiled = try explicitPaths(gpa, "/home/x/.cache/dith", "/models/Ready.mlmodelc");
    defer compiled.deinit(gpa);
    try std.testing.expectEqualStrings("/models/Ready.mlmodelc", compiled.model);
    try std.testing.expectEqualStrings("/models/Ready.mlmodelc", compiled.compiled);
}

test "resolvePaths needs a home directory for the cache" {
    var sink: Io.Writer = .fixed(&.{});
    try std.testing.expectError(ResolveError.NoHomeDirectory, resolvePaths(std.testing.allocator, std.testing.io, null, null, &sink));
}
