const std = @import("std");
const types = @import("types");

// stb_image bindings, generated by translate-c in build.zig
const c = @import("c");

pub const ImageError = error{
    LoadFailed,
    OutOfMemory,
};

/// Owned image data that must be freed
pub const OwnedImage = struct {
    data: []u8,
    width: u32,
    height: u32,
    /// Interleaved 8-bit RGB, kept for depth estimation
    rgb: []u8,
    /// Interleaved CbCr at half resolution (4:2:0), matching the camera layout
    chroma: []u8,
    chroma_width: u32,
    chroma_height: u32,
    allocator: std.mem.Allocator,

    /// Convert to Image for rendering
    pub fn toImage(self: OwnedImage) types.Image {
        return .{
            .data = self.data,
            .width = self.width,
            .height = self.height,
            .bytes_per_row = self.width,
            .chroma = .{
                .data = self.chroma,
                .width = self.chroma_width,
                .height = self.chroma_height,
                .bytes_per_row = self.chroma_width * 2,
            },
        };
    }

    /// Free the image data
    pub fn deinit(self: *OwnedImage) void {
        self.allocator.free(self.data);
        self.allocator.free(self.chroma);
        self.allocator.free(self.rgb);
    }
};

/// Full-range BT.601 RGB -> Y'CbCr, fixed point (8 fractional bits).
/// The luma coefficients are the ones stb_image uses for its own grayscale
/// conversion, so luma output is identical to loading as 1 channel.
pub const YCbCr = struct { y: u8, cb: u8, cr: u8 };

pub inline fn rgbToYCbCr(r: u8, g: u8, b: u8) YCbCr {
    const ri: i32 = r;
    const gi: i32 = g;
    const bi: i32 = b;
    const y = (77 * ri + 150 * gi + 29 * bi) >> 8;
    const cb = 128 + ((-43 * ri - 85 * gi + 128 * bi) >> 8);
    const cr = 128 + ((128 * ri - 107 * gi - 21 * bi) >> 8);
    return .{
        .y = @intCast(@max(0, @min(255, y))),
        .cb = @intCast(@max(0, @min(255, cb))),
        .cr = @intCast(@max(0, @min(255, cr))),
    };
}

/// Load image from file path as luma + subsampled chroma
pub fn load(allocator: std.mem.Allocator, path: []const u8) ImageError!OwnedImage {
    // Null-terminate the path for C
    const c_path = allocator.dupeZ(u8, path) catch return ImageError.OutOfMemory;
    defer allocator.free(c_path);

    var width: c_int = 0;
    var height: c_int = 0;
    var channels: c_int = 0;

    // Load as RGB (3 channels)
    const rgb = c.stbi_load(c_path.ptr, &width, &height, &channels, 3);
    if (rgb == null) {
        return ImageError.LoadFailed;
    }
    defer c.stbi_image_free(rgb);

    const w: u32 = @intCast(width);
    const h: u32 = @intCast(height);
    const cw = (w + 1) / 2;
    const ch = (h + 1) / 2;

    const rgb_copy = allocator.alloc(u8, w * h * 3) catch return ImageError.OutOfMemory;
    errdefer allocator.free(rgb_copy);
    @memcpy(rgb_copy, rgb[0 .. w * h * 3]);

    const luma = allocator.alloc(u8, w * h) catch return ImageError.OutOfMemory;
    errdefer allocator.free(luma);
    const chroma = allocator.alloc(u8, cw * ch * 2) catch return ImageError.OutOfMemory;
    errdefer allocator.free(chroma);

    // Per-pixel luma; chroma accumulated over each 2x2 block
    var cb_sum = allocator.alloc(u32, cw * ch) catch return ImageError.OutOfMemory;
    defer allocator.free(cb_sum);
    var cr_sum = allocator.alloc(u32, cw * ch) catch return ImageError.OutOfMemory;
    defer allocator.free(cr_sum);
    var count = allocator.alloc(u8, cw * ch) catch return ImageError.OutOfMemory;
    defer allocator.free(count);
    @memset(cb_sum, 0);
    @memset(cr_sum, 0);
    @memset(count, 0);

    for (0..h) |y| {
        for (0..w) |x| {
            const src = (y * w + x) * 3;
            const px = rgbToYCbCr(rgb[src], rgb[src + 1], rgb[src + 2]);
            luma[y * w + x] = px.y;
            const ci = (y / 2) * cw + (x / 2);
            cb_sum[ci] += px.cb;
            cr_sum[ci] += px.cr;
            count[ci] += 1;
        }
    }
    for (0..cw * ch) |i| {
        chroma[i * 2] = @intCast(cb_sum[i] / count[i]);
        chroma[i * 2 + 1] = @intCast(cr_sum[i] / count[i]);
    }

    return .{
        .data = luma,
        .width = w,
        .height = h,
        .rgb = rgb_copy,
        .chroma = chroma,
        .chroma_width = cw,
        .chroma_height = ch,
        .allocator = allocator,
    };
}

test "rgbToYCbCr primaries" {
    const white = rgbToYCbCr(255, 255, 255);
    try std.testing.expectEqual(@as(u8, 255), white.y);
    try std.testing.expectEqual(@as(u8, 128), white.cb);
    try std.testing.expectEqual(@as(u8, 128), white.cr);

    const black = rgbToYCbCr(0, 0, 0);
    try std.testing.expectEqual(@as(u8, 0), black.y);
    try std.testing.expectEqual(@as(u8, 128), black.cb);
    try std.testing.expectEqual(@as(u8, 128), black.cr);

    // Pure red: low luma, Cr saturated high, Cb low
    const red = rgbToYCbCr(255, 0, 0);
    try std.testing.expectEqual(@as(u8, 76), red.y);
    try std.testing.expectEqual(@as(u8, 255), red.cr);
    try std.testing.expect(red.cb < 128);

    // Gray has no chroma
    const gray = rgbToYCbCr(100, 100, 100);
    try std.testing.expectEqual(@as(u8, 128), gray.cb);
    try std.testing.expectEqual(@as(u8, 128), gray.cr);
}
